# run configuration
# 'true' to run testbot, 'false' to run the main bot.
testmode: ${TESTMODE}

# bot version
version: 2.1

# bot prefix
prefix:
  main: ㄲ
  test: ㅌㄲ

# discord bot id
bot_id: 703956235900420226

# secret tokens
token:
  main: ${BOT_TOKEN_MAIN}
  test: ${BOT_TOKEN_TEST}
  koreanbots: ${TOKEN_KOREANBOTS}
  dbl: ${TOKEN_DBL}

colors:
  general: 0x4374D9
  error: 0xCC3D3D
  help: 0x47C83E

# list of admin ids that can use admin commands.
admin:
  - 610625541157945344
  - 394116972176080916
  - 759575943211384854

# mongodb configuration
mongo:
  main:
    host: mongo
    port: 27017
    db: kkutbot
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
  test:
    host: mongo
    port: 27017
    db: kkutbot
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
  scheduler:
    hour: "2"
    minute: "47"

# mongodb & log backup channel id
channels:
  backup_data: 838371534690844672
  backup_log: 987017719545229463
  error_log: 1016347873253793832

# sentry dsn for error logging
sentry:
  dsn: ${SENTRY_DSN}
  url: ${SENTRY_URL}

# useful links
links:
  invite:
    bot: https://discord.com/oauth2/authorize?client_id=703956235900420226&scope=bot+applications.commands&permissions=387136&response_type=code&redirect_uri=https%3A%2F%2Fdiscord.gg%2Fz8tRzwf
    server: https://discord.gg/z8tRzwf
  privacy-policy: https://github.com/janu8ry/kkutbot/blob/main/privacy.md
  terms-of-service: https://github.com/janu8ry/kkutbot/blob/main/privacy.md
  koreanbots: https://koreanbots.dev/bots/703956235900420226
  dbl: https://top.gg/bot/703956235900420226
  github: https://github.com/janu8ry/kkutbot
  website: https://kkutbot.github.io
