#################################################################
# +-----------------------------------------------------------+ #
# |                    kkutbot config file                    | #
# +-----------------------------------------------------------+ #
#################################################################

# kkutbot configuration file.
# encoding: utf-8


# run configuration
# 'true' to run testbot, 'false' to run the main bot.
test: true

# secret tokens
token:
  main: main bot token
  test: test bot token
  koreanbots: koreanbots api token
  dbl: top.gg api token
  uniquebots: uniquebots api token

# list of bot ids that can use kkutbot.
bot_whitelist:
  - 00000

# list of admin ids that can use admin commands.
admin:
  - 00000

# webhook url for logging command usages
webhook:
  main: https://discord.com/api/webhooks/channel_id/token
  test: https://discord.com/api/webhooks/channel_id/token

# embed colors
colors:
  general: 0x4374D9
  error: 0xCC3D3D
  help: 0x47C83E

# mongodb configuration
mongo:
  main:
    ip: mongoDB server ip
    port: 27017
    db: kkutbot
    user: mongoDB username  # 'null' if you are not using auth
    password: mongoDB passwd  # 'null' if you are not using auth
  test:
    ip: 127.0.0.1
    port: 27017
    db: kkuttest
    user: mongoDB username  # 'null' if you are not using auth
    password: mongoDB passwd  # 'null' if you are not using auth

# mongodb backup channel id
backup_channel: 0000

# useful links
links:
  invite:
    bot: bot invite url
    server: support server url
  monitoring:
    pm2: pm2 monitoring url
    mongo: mongoDB monitoring url
  koreanbots: koreanbots url
  dbl: top.gg url
  uniquebots: uniquebots url
  github: github repository url
  blog: blog(homepage) url