# docker-compose.yml

version: "3.9"

services:
  kkutbot:
    build:
      context: .
    image: kkutbot:latest
    restart: always
    container_name: "kkutbot"
    volumes:
      - ./logs:/kkutbot/logs
      - ./backup:/storage
    environment:
      - TZ=Asia/Seoul
  mongo:
    image: mongo:4.4.14-focal
    restart: always
    container_name: "kkutbot-mongo"
    ports:
      - "27017:27017"
    volumes:
      -  /Users/janu8ry/Desktop/mongodb:/data/db
    environment:
      - TZ=Asia/Seoul
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
    command: mongod --quiet
    secrets:
      - mongo_username
      - mongo_password
  mongob:
    image: janu8ry/mongob:arm64
    restart: always
    container_name: "kkutbot-mongob"
    volumes:
      - ./mongob.yml:/mongob/config.yml
      - ./backup:/backup
    environment:
      - TZ=Asia/Seoul

secrets:
  mongo_username:
    file: mongo_username.txt
  mongo_password:
    file: mongo_password.txt
