# docker-compose.yml

version: "3.9"

services:
  kkutbot:
    build:
      context: .
    image: kkutbot:latest
    restart: always
    container_name: "kkutbot"
    volumes:
      - ./logs:/kkutbot/logs
      - ./backup:/backup
    environment:
      - TZ=Asia/Seoul
  mongo:
    image: mongo:4.4.14-focal
    restart: always
    container_name: "kkutbot-mongo"
    ports:
      - "27017:27017"
    volumes:
      -  /Users/janu8ry/Desktop/mongodb:/data/db
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: mongod --quiet
  mongob:
    image: janu8ry/mongob:arm64
    restart: always
    container_name: "kkutbot-mongob"
    volumes:
      - ./mongob.yml:/mongob/config.yml
      - ./backup:/backup
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - MONGOB_USERNAME=${MONGO_USERNAME}
      - MONGOB_PASSWORD=${MONGO_PASSWORD}
