# docker-compose.yml

version: "3.7"

services:
  kkutbot:
    build: .
    image: kkutbot:latest
    restart: always
    container_name: "kkutbot"
    volumes:
      - ./logs:/kkutbot/logs
  mongo:
    image: mongo:4.4.14-focal
    restart: always
    container_name: "kkutbot-mongo"
    ports:
      - "27017:27017"
    volumes:
      -  /var/lib/mongodb:/data/db
  mgob:
    image: stefanprodan/mgob:latest
    restart: always
    container_name: "kkutbot-mgob"
    ports:
      - "8090:8090"
    volumes:
      - ./mgob.yml:/config/mgob.yml
      - ./backup:/storage
      - ./mgob_tmp:/tmp
      - ./mgob_data:/data