# docker-compose.yml

version: "3"

services:
  kkutbot:
    build: .
    image: kkutbot:latest
    restart: always
    container_name: "kkutbot"
    volumes:
      - ./logs:/kkutbot/logs
  mongo:
    image: mongo:latest
    restart: always
    container_name: "kkutbot-mongo"
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb:/data/db
      - ./mongod.conf:/etc/mongod.conf
    env_file:
      - mongo.env
  mgob:
    image: stefanprodan/mgob:latest
    restart: always
    container_name: "kkutbot-mgob"
    ports:
      - "8090:8090"
    volumes:
      - ./mgob.example.yml:/config/mgob.example.yml
      - ./backup:/storage
      - ./mgob_tmp:/tmp
      - ./mgob_data:/data
