# docker-compose.yml

version: "3"

services:
  kkutbot:
    build: .
    image: kkutbot:latest
    restart: always
    container_name: "kkutbot"
    volumes:
      - ./logs:/kkutbot/logs
      - ./backup:./backup
  mongo:
    image: mongo:latest
    restart: always
    container_name: "kkutbot-mongo"
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb:/data/db
    env_file:
      - mongo.env