services:
  kkutbot:
    build:
      context: .
    image: kkutbot:latest
    restart: always
    container_name: "kkutbot"
    volumes:
      - ./logs:/kkutbot/logs
      - ./backup:/kkutbot/backup
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
  mongo:
    image: mongo:7.0.37
    restart: always
    container_name: "kkutbot-mongo"
    ports:
      - "27017:27017"
    volumes:
      - ${DBPATH}:/data/db
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: mongod --quiet
  dbgate:
    image: dbgate/dbgate:latest
    restart: always
    container_name: "kkutbot-dbgate"
    ports:
      - "8081:3000"
    volumes:
      - dbgate-data:/root/.dbgate
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - CONNECTIONS=kkutbot
      - LABEL_kkutbot=kkutbot
      - URL_kkutbot=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/?authSource=admin
      - ENGINE_kkutbot=mongo@dbgate-plugin-mongo
      - LOGIN=${DBGATE_LOGIN}
      - PASSWORD=${DBGATE_PASSWORD}
    depends_on:
      - mongo
  mongob:
    image: janu8ry/mongob:arm64
    restart: always
    container_name: "kkutbot-mongob"
    volumes:
      - ./config.yml:/mongob/config.yml
      - ./backup:/backup
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mongo

volumes:
  dbgate-data:
