[tool.poetry]
name = "kkutbot"
version = "2.1.0-alpha"
description = "끝말잇기 디스코드봇"
authors = ["janu8ry <janu8ry0108@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
homepage = "https://kkutbot.github.io"
repository = "https://github.com/janu8ry/kkutbot"

[tool.poetry.dependencies]
python = "~3.10"
"discord.py" = {extras = ["speed"], version = "~2.3.1"}

[tool.poetry.dev-dependencies]
isort = "~5.11.2"
flake8 = "~5.0.4"
mypy = "~1.3"

[tool.isort]
skip_gitignore = true
line_length = "150"
extra_standard_library = ["typing_extensions"]

[tool.mypy]
strict = false
warn_unused_configs = true
show_error_codes = true
disable_error_code = "misc"
exclude = ".venv"

[[tool.mypy.overrides]]
module = ["discord.*", "motor.*", "apscheduler.*", "yaml.*", "rich.*", "koreanbots.*", "topgg.*", "psutil.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["tools.views"]
ignore_errors = true

[tool.poetry.urls]
Invite = "https://discord.com/api/oauth2/authorize?client_id=703956235900420226&permissions=387136&scope=bot"
discord = "https://discord.gg/z8tRzwf"
koreanbots = "https://koreanbots.dev/bots/703956235900420226"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

