[tool.poetry]
name = "kkutbot"
version = "1.7.0"
description = "끝말잇기 디스코드봇"
authors = ["janu8ry <janu8ry0108@gmail.com>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = "^1.7.2"
PyYAML = "^5.4.1"
pymongo = "^3.11.3"
koreanbots = "^0.2.3"
UniqueBotsKR = "^1.3"
APScheduler = "^3.7.0"
meval = "^2.5"
psutil = "^5.8.0"
humanize = "^3.3.0"
dblpy = "^0.4.0"
jishaku = "^1.20.0.220"
dhooks = "^1.1.4"
aiohttp = {version = "^3.7.3", extras = ["speedups"]}

[tool.poetry.dev-dependencies]
isort = "^5.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
