[tool.poetry]
name = "kkutbot"
version = "2.0.0-alpha"
description = "끝말잇기 디스코드봇"
authors = ["janu8ry <janu8ry0108@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
homepage = "https://kkutbot.github.io"
repository = "https://github.com/janu8ry/kkutbot"

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^5.4.1"
motor = "^2.4.0"
uvloop = "^0.15.2"
"discord.py" = "^1.7.3"
aiohttp = {extras = ["speedups"], version = "^3.7.4"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
