name: Isort

on:
  push:
    branches:
      - master
      - rewrite
  pull_request:
    branches:
      - master
      - rewrite

jobs:
  isort:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip3 install -r isort
      - name: Sort with isort
        run: |
          isort . --gitignore
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor: isort"
          commit_user_name: Isort Action
